server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/admin-radar?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 233031
#  redis:
#    host: localhost
#    port: 6379 #端口
#    database: 0 # 数据库
#    connect-timeout: 10000ms #超时时间
#    lettuce:
#      pool:
#        max-active: 8 #最大连接数
#        max-wait: 10000ms # 最大连接阻塞等待时间
#        max-idle: 200 # 最大空闲时间
#        min-idle: 5 #最小空闲连接

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

# JWT 配置
jwt:
  tokenHeader: Authorization
  secret: admin-radar
  expiration: 604800
  tokenHead: Bearer